.PHONY: all test clean sub_test sub_test_clean

CFLAGS += -std=c17 -O3 -Wall -pedantic -Werror -I..

all: .mdp_run
	@$(MAKE) test

.mdp_run: $(wildcard *.md)
	@[ -x "$$(command -v mdp)" ] || echo "mdp not installed" 1>&2
	@[ -x "$$(command -v mdp)" ] && mdp README.md
	@date >$@

%.o: %.c
	@echo cc $@
	@$(CC) $(CFLAGS) -c $<

sub_test:
	@$(MAKE) --directory=tests

sub_test_clean:
	@$(MAKE) --directory=tests clean
